In [ ]:
!pip install -U bitsandbytes datasets huggingface_hub transformers peft accelerate sentencepiece
# === Imports & GPU check ===
import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    BitsAndBytesConfig
)
from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training
)

Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.48.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.2.0)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.35.3)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.17.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.10.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.8.0+cu126)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (25.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.19.1)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.1.10)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.12.15)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)

In [ ]:
import os
from torch.utils.data import TensorDataset, DataLoader

print("torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
  print("GPU:", torch.cuda.get_device_name(0))

torch: 2.8.0+cu126
CUDA available: True
GPU: Tesla T4

In [ ]:
MODEL_NAME = "mistralai/Mistral-7B-v0.1"   # change if you want (LLaMA-3, etc.)
MAX_INPUT_LENGTH = 512
MAX_TARGET_LENGTH = 128
TRAIN_EXAMPLES = 2000    # lower for quick tests
EVAL_EXAMPLES = 200
BATCH_SIZE = 1           # per device (use gradient_accumulation for effective larger batch)
GRAD_ACCUM_STEPS = 4
LEARNING_RATE = 2e-4
EPOCHS = 1
OUTPUT_DIR = "./mistral_qloar_results"

# === Load dataset (we will avoid dataset.map) ===
dataset = load_dataset("ccdv/arxiv-summarization")
print(dataset)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

DatasetDict({
    train: Dataset({
        features: ['article', 'abstract'],
        num_rows: 203037
    })
    validation: Dataset({
        features: ['article', 'abstract'],
        num_rows: 6436
    })
    test: Dataset({
        features: ['article', 'abstract'],
        num_rows: 6440
    })
})

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, use_fast=True)
# ensure pad token exists
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# === Load model in 4-bit (QLoRA) using bitsandbytes ===
print("Loading model in 4-bit (QLoRA) ... this may take a moment")

from transformers import BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
    trust_remote_code=False  # set True if model requires remote code; usually False is safer
)

`torch_dtype` is deprecated! Use `dtype` instead!

Loading model in 4-bit (QLoRA) ... this may take a moment

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
model = prepare_model_for_kbit_training(model)  # sets requires_grad appropriate, enables gradient checkpointing etc.

# === LoRA config and apply LoRA ===
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj"],  # good default for many transformer implementations
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()  # ch

trainable params: 6,815,744 || all params: 7,248,547,840 || trainable%: 0.0940

In [ ]:
def tokenize_examples(batch):
    # batch is a dict-style HuggingFace slice: e.g. dataset["train"][:N]
    inputs = ["Summarize this document:\n" + doc for doc in batch["article"]]
    tokenized = tokenizer(
        inputs,
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
        padding=True,        # padding added here to create tensors of same length
        return_tensors="pt"
    )
    targets = tokenizer(
        batch["abstract"],
        max_length=MAX_TARGET_LENGTH,
        truncation=True,
        padding=True, # padding added here
        return_tensors="pt"
    )
    # labels will be the token ids of targets; for causal LM Trainer expects labels aligned
    tokenized["labels"] = targets["input_ids"]
    return tokenized

In [ ]:
train_slice = dataset["train"][:TRAIN_EXAMPLES]
eval_slice = dataset["validation"][:EVAL_EXAMPLES]

train_tok = tokenize_examples(train_slice)
eval_tok = tokenize_examples(eval_slice)

# Build TensorDatasets of variable-length sequences is awkward; instead we store lists and write a collator
train_examples = list(zip(train_tok["input_ids"], train_tok["attention_mask"], train_tok["labels"]))
eval_examples = list(zip(eval_tok["input_ids"], eval_tok["attention_mask"], eval_tok["labels"]))

In [ ]:
from torch.utils.data import Dataset

class SimpleListDataset(Dataset):
    def __init__(self, examples):
        self.examples = examples
    def __len__(self):
        return len(self.examples)
    def __getitem__(self, idx):
        input_ids, attn_mask, labels = self.examples[idx]
        return {"input_ids": input_ids, "attention_mask": attn_mask, "labels": labels}

train_dataset = SimpleListDataset(train_examples)
eval_dataset = SimpleListDataset(eval_examples)

In [ ]:
def collate_fn(batch):
    # batch is a list of dicts with tensors of different lengths
    input_ids = [b["input_ids"] for b in batch]
    attn = [b["attention_mask"] for b in batch]
    labels = [b["labels"] for b in batch]

    # pad
    input_ids_padded = torch.nn.utils.rnn.pad_sequence(input_ids, batch_first=True, padding_value=tokenizer.pad_token_id)
    attn_padded = torch.nn.utils.rnn.pad_sequence(attn, batch_first=True, padding_value=0)

    # Pad labels to the same length as input_ids_padded
    labels_padded = torch.nn.utils.rnn.pad_sequence(labels, batch_first=True, padding_value=-100)  # -100 ignored by loss
    if labels_padded.shape[1] < input_ids_padded.shape[1]:
        padding_length = input_ids_padded.shape[1] - labels_padded.shape[1]
        labels_padded = torch.nn.functional.pad(labels_padded, (0, padding_length), "constant", -100)
    elif labels_padded.shape[1] > input_ids_padded.shape[1]:
         # This case should ideally not happen with truncation, but added for robustness
         labels_padded = labels_padded[:, :input_ids_padded.shape[1]]


    print(f"Shape of padded input_ids: {input_ids_padded.shape}")
    print(f"Shape of padded labels: {labels_padded.shape}")


    return {
        "input_ids": input_ids_padded,
        "attention_mask": attn_padded,
        "labels": labels_padded
    }

In [ ]:
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRAD_ACCUM_STEPS,
    learning_rate=LEARNING_RATE,
    num_train_epochs=EPOCHS,
    fp16=True,
    logging_steps=20,
    save_strategy="epoch",   # avoid eval if your transformers version complains; set to "epoch" if supported
    report_to="none",
    save_total_limit=2,
    dataloader_pin_memory=True,
)

# === Trainer ===
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=collate_fn,
)

# === Train ===
trainer.train()

# === Save LoRA adapters (saves small weights) ===
peft_save_dir = os.path.join(OUTPUT_DIR, "lora-adapter")
model.save_pretrained(peft_save_dir)
print("Saved LoRA adapters to:", peft_save_dir)

# === Quick inference test (on CPU or GPU depending where model resides) ===
sample_text = dataset["test"][0]["article"]
prompt = "Summarize this document:\n" + sample_text[:2000]  # shorten to keep inference fast
inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=MAX_INPUT_LENGTH)
# move inputs to same device as model's first param
device = next(model.parameters()).device
inputs = {k: v.to(device) for k, v in inputs.items()}
out = model.generate(**inputs, max_new_tokens=100)
print("SUMMARY:\n", tokenizer.decode(out[0], skip_special_tokens=True))

Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])

Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])
Shape of padded input_ids: torch.Size([1, 512])
Shape of padded labels: torch.Size([1, 512])

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Caching is incompatible with gradient checkpointing in MistralDecoderLayer. Setting `past_key_values=None`.

Saved LoRA adapters to: ./mistral_qloar_results/lora-adapter

/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py:929: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.5 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/torch/utils/checkpoint.py:85: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

SUMMARY:
 Summarize this document:
for about 20 years the problem of properties of short - term changes of solar activity has been considered extensively .
 many investigators studied the short - term periodicities of the various indices of solar activity .
 several periodicities were detected , but the periodicities about 155 days and from the interval of @xmath3 $ ] days ( @xmath4 $ ] years ) are mentioned most often .
 first of them was discovered by @xcite in the occurence rate of gamma - ray flares detected by the gamma - ray spectrometer aboard the _ solar maximum mission ( smm ) .
 this periodicity was confirmed for other solar flares data and for the same time period @xcite .
 it was also found in proton flares during solar cycles 19 and 20 @xcite , but it was not found in the solar flares data during solar cycles 22 @xcite .
 _    several autors confirmed above results for the daily sunspot area data . @xcite studied the sunspot data from 18741984 .
 she found the 155-day periodicity in data records from 31 years .
 this periodicity is always characteristic for one of the solar hemispheres ( the southern hemisphere for cycles 1215 and the northern hemisphere for cycles 1621 ) .
 moreover , it is only present during epochs of maximum activity ( in episodes of 13 years ) .
 similarinvestigationswerecarriedoutby + @xcite .
 they applied the same power spectrum method as lean , but the daily sunspot area data ( cycles 1221 ) were divided into 10 shorter time series .
 the periodicities were searched for the frequency interval 57115 nhz ( 100200 days ) and for each of 10 time series .
 the authors showed that the periodicity between 150160 days is statistically significant during all cycles from 16 to 21 .
 the considered peaks were remained unaltered after removing the 11-year cycle and applying the power spectrum analysis .
 @xcite used the wavelet technique for the daily sunspot areas between 1 the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the the